### PR TITLE
Add new & corrected flowcharts for RXNO documentation

### PR DESCRIPTION
**Pull request by hujo91**
Hi @batchelorc please take a look at our suggestions for improving the RXNO documentation. Thanks!

1. [docs/flowchart_reaction.svg](https://github.com/NFDI4Chem/rxno/blob/update-documentation/docs/flowchart_reaction.svg)  adds a graphical flowchart for human contributors, based on  [docs/20190902_Ontoposter.pptx](https://github.com/NFDI4Chem/rxno/blob/master/docs/20190902_Ontoposter.pptx). It was revised with respect to the inconsistencies described in #9,  concerning the inclusion of new reactions into the correct parent class.

The following image highlights (in purple) the changes made to  [docs/flowchart_reaction.svg](https://github.com/NFDI4Chem/rxno/blob/update-documentation/docs/flowchart_reaction.svg) 

flowchart_reaction_corrected_marked

2. [docs/flowchart_skeleton.svg](https://github.com/NFDI4Chem/rxno/blob/update-documentation/docs/flowchart_skeleton.svg) is a new graphical flowchart for assigning the skeleton of a chemical molecule, which should help complement  [docs/flowchart_skeleton.md](https://github.com/rsc-ontologies/rxno/blob/master/docs/flowchart_skeleton.md).

### CODE REVIEW

**Review by StroemPhi — APPROVED** [review]

**Comment by andrecastro0o** [comment]
@hujo91 :+1:

**Comment by andrecastro0o** [comment]
@hujo91 I am wondering if it is not better to submit the flowchart as a SVG file, so that further changes can be made to it, without needing to create a new image....but it depends on how the flowchart png was created, but I thing the SVG is a better approach

**Comment by hujo91** [comment]
Converted the flowcharts from png to svg file format and uploaded the new svg files in the corresponding [GDrive folder](https://drive.google.com/drive/folders/1idgiY2DoWA2zAOmp7M1-ghcI3H4Jqcjx)
in addition I attach here all files relevant for this commit again collected as zip-file ([RXNO_flowcharts.zip](https://github.com/NFDI4Chem/rxno/files/6614452/RXNO_flowcharts.zip))

**Comment by andrecastro0o** [comment]
@hujo91 should:
* add the SVG version files of the flowcharts
* remove the png

@andrecastro0o will then
 * then clean the SVG so that is suitable to later editing (since text elements are a bit wonky)

**Comment by andrecastro0o** [comment]
@hujo91  when the PR is ready to go to RXNO a remove `Draft:` from the title

**Comment by rsc-ontologies** [comment]
Hello - looks good! Many thanks!
* In the case of several "equal" reaction partners, take the one that contributes the larger number of atoms to the part of the product of interest.
* Only apply the rules of the scheme to the product if it is difficult to determine the skeleton from the starting material.

**Comment by hujo91** [comment]
@andrecastro0o I have included RSC-ontologies' answers to the outstanding questions in the notes at Skeleton Flowchart and updated the pptx file and Skeleton svg file accordingly. Also, I removed the paragraph with the questions, then from the top comment and also deleted the draft from the title. Thus, in my opinion, this PR can now go out. :-)

**Pull request merged**
